resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: EldadaGitHub
      path: eldada/jfrog-pipes-test

  - name: fileSpecCody
    type: FileSpec
    configuration:
      sourceArtifactory: EldadaArtifactory
      pattern: "generic-local/cat/"
      target: $pipeline_workspace_dir
     
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_run_variables current_runid=$run_id
            - echo Previous run ID is $prev_runid
            - echo Current run ID is $current_runid
            - echo res_myAppRepo_resourcePath is $res_myAppRepo_resourcePath
            - echo res_myAppRepo_gitProvider_name is $res_myAppRepo_gitProvider_name
            - echo res_myAppRepo_commitSha is $res_myAppRepo_commitSha
 
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
 
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
 
      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_pipeline_variables prev_runid=$run_id           

      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_4
        execution:
          onExecute:
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - add_pipeline_variables prev_runid=$run_id           
            - echo $current_runid Completed
            - echo TESTS COMPLETE

      - name: step_6
        type: Bash
        configuration:
          inputSteps:
            - name: step_5
          inputResources:
            - name: fileSpecCody
        execution:
          onExecute:
            - echo "File spec download path is $res_fileSpecCody_resourcePath"
            - ls -la $res_fileSpecCody_resourcePath
    
