pipelines:
  - name: my_first_pipeline
    steps:
      - name: myFirstStep
        type: Bash
        execution:
          onExecute:
            - env | sort
            - docker version
            - docker ps -a
            - echo "----------- DONE -----------"
