pipelines:
  - name: my_first_pipeline
    steps:
      - name: myFirstStep
        type: Bash
        execution:
          onExecute:
            - echo "============"
            - echo "Hello world!"
            - echo "============"
